SET NAMES UTF8;
DROP DATABASE IF EXISTS nx;
CREATE DATABASE nx CHARSET=utf8;
USE nx;

/*商品家族表*/
CREATE TABLE product_family(
	family_id INT PRIMARY KEY AUTO_INCREMENT,	#商品类型编号
	family_name VARCHAR(32)				#商品类型名称
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*插入商品家族表数据*/
INSERT INTO product_family VALUES(NULL,'蛋糕');
INSERT INTO product_family VALUES(NULL,'吐司');
INSERT INTO product_family VALUES(NULL,'礼品');

/*商品表*/
CREATE TABLE product_info(
	product_id INT PRIMARY KEY AUTO_INCREMENT, #商品编号
	fid INT,					#商品类型编号
	FOREIGN KEY(fid) REFERENCES product_family(family_id),

	title VARCHAR(32),          #主标题
	subtitle VARCHAR(64),       #副标题
	tag VARCHAR(64),            #商品标签
	price DECIMAL(10,2),        #商品价格
	dilivery   VARCHAR(32),     #商品配送时间
	shelf_time DATE,			#上架时间
	sold_count INT,             #商品已售数量

	taste VARCHAR(32),          #商品口味
	spec VARCHAR(32),           #商品规格
	sweet VARCHAR(32),          #商品甜度
	size VARCHAR(32),           #商品尺寸
	size_img VARCHAR(64),       #商品尺寸图片
	people VARCHAR(32),         #商品食用人数
	tableware VARCHAR(32),      #商品餐具数量
	storage_methods VARCHAR(64),			#商品保存条件
	marterials VARCHAR(128),    #商品原材料
	raw_material VARCHAR(128),  #商品原材料产地

	details VARCHAR(2048),      #商品详情
	is_onsale BOOLEAN DEFAULT 1 #商品在售
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;
/*插入商品表数据*/
INSERT INTO product_info VALUES(NULL,1,'盛夏·彩虹千层蛋糕',	NULL,'HOT',318.00,'最早明天10:00配送','1539532800000',10,'鲜果口味','1.0磅','2','约13.5×13.5cm','img/products/details/spec (1).png','适合3-5人分享','含5套餐具','0-4℃保藏10小时，5℃食用为佳','无盐黄油,稀奶油','新西兰,法国/德国','<div><img src="img/products/details/1_1_1 (2).jpg" alt=""></div><div><img src="img/products/details/1_1_1 (1).jpg" alt=""></div><div class="fruit-details"><div class="fruitImg-details"><img src="img/products/details/mango.jpg" class="img-md"></div><div class="fruitTxt-details"><p>金黄色的芒果</p><p>蕴藏着敦厚的果肉</p><p>香滑甜蜜的口感</p><p>让人想起阳光的滋味</p></div></div><div class="fruit-details"><div class="fruitTxt-details"><p>草莓薰红的季节</p><p>带来满口的酸甜</p><p>原汁原味</p><p>鲜丽诱人</p></div><div class="fruitImg-details"><img src="img/products/details/strawberry (1).jpg" class="img-md"></div></div><div class="fruit-details"><div class="fruitImg-details"><img src="img/products/details/cantaloupe.jpg" class="img-md"></div><div class="fruitTxt-details"><p>淡青色的甜瓜</p><p>每一口都清香柔嫩</p><p>甜蜜无孔不入</p><p>充盈在唇齿间</p></div></div><div class="fruit-details"><div class="fruitTxt-details"><p>新鲜的蓝莓</p><p>与蛋糕的精心配比</p><p>酸甜清爽</p><p>回味无穷</p></div><div class="fruitImg-details"><img src="img/products/details/blueberries.jpg" class="img-md"></div></div><div class="fruit-details"><div class="fruitImg-details"><img src="img/products/details/banana.jpg" class="img-md"></div><div class="fruitTxt-details"><p>黄澄澄的香蕉</p><p>人见人爱的微笑水果</p><p>饱满的果肉 甜甜的香气</p><p>让人一吃就停不下来</p></div></div><div class="fruit-details"><div class="fruitTxt-details"><p>黄金奶源地高品质奶源</p><p>香浓又健康</p><p>让你与大自然更亲近</p></div><div class="fruitImg-details"><img src="img/products/details/milk.jpg" class="img-md"></div></div>',1);
INSERT INTO product_info VALUES(NULL,1,'盛夏·彩虹千层蛋糕',NULL,'HOT',488.00,'最早明天10:00配送','1539532800000',10,'鲜果口味','4.0磅','2','约25.5×25.5cm','img/products/details/spec (4).png','适合10-12人分享','含20套餐具','0-4℃保藏10小时，5℃食用为佳','无盐黄油,稀奶油','新西兰,法国/德国','<div><img src="img/products/details/1_1_1 (2).jpg" alt=""></div><div><img src="img/products/details/1_1_1 (1).jpg" alt=""></div><div class="fruit-details"><div class="fruitImg-details"><img src="img/products/details/mango.jpg" class="img-md"></div><div class="fruitTxt-details"><p>金黄色的芒果</p><p>蕴藏着敦厚的果肉</p><p>香滑甜蜜的口感</p><p>让人想起阳光的滋味</p></div></div><div class="fruit-details"><div class="fruitTxt-details"><p>草莓薰红的季节</p><p>带来满口的酸甜</p><p>原汁原味</p><p>鲜丽诱人</p></div><div class="fruitImg-details"><img src="img/products/details/strawberry (1).jpg" class="img-md"></div></div><div class="fruit-details"><div class="fruitImg-details"><img src="img/products/details/cantaloupe.jpg" class="img-md"></div><div class="fruitTxt-details"><p>淡青色的甜瓜</p><p>每一口都清香柔嫩</p><p>甜蜜无孔不入</p><p>充盈在唇齿间</p></div></div><div class="fruit-details"><div class="fruitTxt-details"><p>新鲜的蓝莓</p><p>与蛋糕的精心配比</p><p>酸甜清爽</p><p>回味无穷</p></div><div class="fruitImg-details"><img src="img/products/details/blueberries.jpg" class="img-md"></div></div><div class="fruit-details"><div class="fruitImg-details"><img src="img/products/details/banana.jpg" class="img-md"></div><div class="fruitTxt-details"><p>黄澄澄的香蕉</p><p>人见人爱的微笑水果</p><p>饱满的果肉 甜甜的香气</p><p>让人一吃就停不下来</p></div></div><div class="fruit-details"><div class="fruitTxt-details"><p>黄金奶源地高品质奶源</p><p>香浓又健康</p><p>让你与大自然更亲近</p></div><div class="fruitImg-details"><img src="img/products/details/milk.jpg" class="img-md"></div></div>',1);
INSERT INTO product_info VALUES(NULL,1,'草莓拿破仑蛋糕',NULL,'NEW,HOT',198.00,'最早明天10:00配送','1539532800000',10,'鲜果口味','1.0磅','3','约13.5×13.5cm','img/products/details/spec (1).png','适合3-4人分享','含5套餐具','0-4℃保藏10小时，5℃食用为佳','幼砂糖,黄油,淡奶油','韩国,法国/新西兰,法国/新西兰','<div><img src="img/products/details/1_1_2 (2).jpg" alt=""></div><div><img src="img/products/details/1_1_2 (1).jpg" alt=""></div><div class="fruit-details"><div class="fruitImg-details"><img src="img/products/details/cream.jpg" class="img-md"></div><div class="fruitTxt-details"><p>手工打发而成的美味奶油</p><p>口感绵密，精致细腻</p><p>这份雪白让你有如获至宝的幸福感</p></div></div><div class="fruit-details"><div class="fruitTxt-details"><p>草莓薰红的季节</p><p>带来满口的酸甜</p><p>原汁原味</p><p>鲜丽诱人</p></div><div class="fruitImg-details"><img src="img/products/details/strawberry (2).jpg" class="img-md"></div></div>',1);
INSERT INTO product_info VALUES(NULL,1,'草莓拿破仑蛋糕',NULL,'NEW,HOT',298.00,'最早明天10:00配送','1539532800000',10,'鲜果口味','2.0磅','3','约17.5×17.5cm','img/products/details/spec (2).png','适合5-8人分享','含10套餐具','0-4℃保藏10小时，5℃食用为佳','幼砂糖,黄油,淡奶油','韩国,法国/新西兰,法国/新西兰','<div><img src="img/products/details/1_1_2 (2).jpg" alt=""></div><div><img src="img/products/details/1_1_2 (1).jpg" alt=""></div><div class="fruit-details"><div class="fruitImg-details"><img src="img/products/details/cream.jpg" class="img-md"></div><div class="fruitTxt-details"><p>手工打发而成的美味奶油</p><p>口感绵密，精致细腻</p><p>这份雪白让你有如获至宝的幸福感</p></div></div><div class="fruit-details"><div class="fruitTxt-details"><p>草莓薰红的季节</p><p>带来满口的酸甜</p><p>原汁原味</p><p>鲜丽诱人</p></div><div class="fruitImg-details"><img src="img/products/details/strawberry (2).jpg" class="img-md"></div></div>',1);
INSERT INTO product_info VALUES(NULL,1,'草莓拿破仑蛋糕',NULL,'NEW,HOT',398.00,'最早明天10:00配送','1539532800000',10,'鲜果口味','3.0磅','3','约22.5×22.5cm','img/products/details/spec (3).png','适合8-10人分享','含15套餐具','0-4℃保藏10小时，5℃食用为佳','幼砂糖,黄油,淡奶油','韩国,法国/新西兰,法国/新西兰','<div><img src="img/products/details/1_1_2 (2).jpg" alt=""></div><div><img src="img/products/details/1_1_2 (1).jpg" alt=""></div><div class="fruit-details"><div class="fruitImg-details"><img src="img/products/details/cream.jpg" class="img-md"></div><div class="fruitTxt-details"><p>手工打发而成的美味奶油</p><p>口感绵密，精致细腻</p><p>这份雪白让你有如获至宝的幸福感</p></div></div><div class="fruit-details"><div class="fruitTxt-details"><p>草莓薰红的季节</p><p>带来满口的酸甜</p><p>原汁原味</p><p>鲜丽诱人</p></div><div class="fruitImg-details"><img src="img/products/details/strawberry (2).jpg" class="img-md"></div></div>',1);
INSERT INTO product_info VALUES(NULL,1,'草莓拿破仑蛋糕',NULL,'NEW,HOT',498.00,'最早明天10:00配送','1539532800000',10,'鲜果口味','4.0磅','3','约25.5×25.5cm','img/products/details/spec (4).png','适合10-12人分享','含20套餐具','0-4℃保藏10小时，5℃食用为佳','幼砂糖,黄油,淡奶油','韩国,法国/新西兰,法国/新西兰','<div><img src="img/products/details/1_1_2 (2).jpg" alt=""></div><div><img src="img/products/details/1_1_2 (1).jpg" alt=""></div><div class="fruit-details"><div class="fruitImg-details"><img src="img/products/details/cream.jpg" class="img-md"></div><div class="fruitTxt-details"><p>手工打发而成的美味奶油</p><p>口感绵密，精致细腻</p><p>这份雪白让你有如获至宝的幸福感</p></div></div><div class="fruit-details"><div class="fruitTxt-details"><p>草莓薰红的季节</p><p>带来满口的酸甜</p><p>原汁原味</p><p>鲜丽诱人</p></div><div class="fruitImg-details"><img src="img/products/details/strawberry (2).jpg" class="img-md"></div></div>',1);
INSERT INTO product_info VALUES(NULL,1,'蓝莓拿破仑蛋糕',NULL,'NEW',198.00,'最早明天10:00配送','1539532800000',10,'鲜果口味','1.0磅','3','约13.5×13.5cm','img/products/details/spec (1).png','适合3-4人分享','含5套餐具','0-4℃保藏10小时，5℃食用为佳','幼砂糖,黄油,淡奶油','韩国,法国/新西兰,法国/新西兰','<div><img src="img/products/details/1_1_3 (2).jpg" alt=""></div><div><img src="img/products/details/1_1_3 (1).jpg" alt=""></div><div class="fruit-details"><div class="fruitImg-details"><img src="img/products/details/cream.jpg" class="img-md"></div><div class="fruitTxt-details"><p>手工打发而成的美味奶油</p><p>口感绵密，精致细腻</p><p>这份雪白让你有如获至宝的幸福感</p></div></div><div class="fruit-details"><div class="fruitTxt-details"><p>新鲜的蓝莓</p><p>与蛋糕的精心配比</p><p>酸甜清爽</p><p>回味无穷</p></div><div class="fruitImg-details"><img src="img/products/details/blueberries.jpg" class="img-md"></div></div>',1);
INSERT INTO product_info VALUES(NULL,1,'蓝莓拿破仑蛋糕',NULL,'NEW',298.00,'最早明天10:00配送','1539532800000',10,'鲜果口味','2.0磅','3','约17.5×17.5cm','img/products/details/spec (2).png','适合5-8人分享','含10套餐具','0-4℃保藏10小时，5℃食用为佳','幼砂糖,黄油,淡奶油','韩国,法国/新西兰,法国/新西兰','<div><img src="img/products/details/1_1_3 (2).jpg" alt=""></div><div><img src="img/products/details/1_1_3 (1).jpg" alt=""></div><div class="fruit-details"><div class="fruitImg-details"><img src="img/products/details/cream.jpg" class="img-md"></div><div class="fruitTxt-details"><p>手工打发而成的美味奶油</p><p>口感绵密，精致细腻</p><p>这份雪白让你有如获至宝的幸福感</p></div></div><div class="fruit-details"><div class="fruitTxt-details"><p>新鲜的蓝莓</p><p>与蛋糕的精心配比</p><p>酸甜清爽</p><p>回味无穷</p></div><div class="fruitImg-details"><img src="img/products/details/blueberries.jpg" class="img-md"></div></div>',1);
INSERT INTO product_info VALUES(NULL,1,'蓝莓拿破仑蛋糕',NULL,'NEW',398.00,'最早明天10:00配送','1539532800000',10,'鲜果口味','3.0磅','3','约22.5×22.5cm','img/products/details/spec (3).png','适合8-10人分享','含15套餐具','0-4℃保藏10小时，5℃食用为佳','幼砂糖,黄油,淡奶油','韩国,法国/新西兰,法国/新西兰','<div><img src="img/products/details/1_1_3 (2).jpg" alt=""></div><div><img src="img/products/details/1_1_3 (1).jpg" alt=""></div><div class="fruit-details"><div class="fruitImg-details"><img src="img/products/details/cream.jpg" class="img-md"></div><div class="fruitTxt-details"><p>手工打发而成的美味奶油</p><p>口感绵密，精致细腻</p><p>这份雪白让你有如获至宝的幸福感</p></div></div><div class="fruit-details"><div class="fruitTxt-details"><p>新鲜的蓝莓</p><p>与蛋糕的精心配比</p><p>酸甜清爽</p><p>回味无穷</p></div><div class="fruitImg-details"><img src="img/products/details/blueberries.jpg" class="img-md"></div></div>',1);
INSERT INTO product_info VALUES(NULL,1,'蓝莓拿破仑蛋糕',NULL,'NEW',498.00,'最早明天10:00配送','1539532800000',10,'鲜果口味','5.0磅','3','约28.5×28.5cm','img/products/details/spec (5).png','适合13-16人分享','含25套餐具','0-4℃保藏10小时，5℃食用为佳','幼砂糖,黄油,淡奶油','韩国,法国/新西兰,法国/新西兰','<div><img src="img/products/details/1_1_3 (2).jpg" alt=""></div><div><img src="img/products/details/1_1_3 (1).jpg" alt=""></div><div class="fruit-details"><div class="fruitImg-details"><img src="img/products/details/cream.jpg" class="img-md"></div><div class="fruitTxt-details"><p>手工打发而成的美味奶油</p><p>口感绵密，精致细腻</p><p>这份雪白让你有如获至宝的幸福感</p></div></div><div class="fruit-details"><div class="fruitTxt-details"><p>新鲜的蓝莓</p><p>与蛋糕的精心配比</p><p>酸甜清爽</p><p>回味无穷</p></div><div class="fruitImg-details"><img src="img/products/details/blueberries.jpg" class="img-md"></div></div>',1);
INSERT INTO product_info VALUES(NULL,1,'她的蛋糕',NULL,'HOT',298.00,'最早明天10:00配送','1539532800000',10,'鲜果口味','2.0磅','4','约17.5×17.5cm','img/products/details/spec (2).png','适合5-8人分享','含10套餐具','0-4℃保藏10小时，5℃食用为佳','白巧克力,稀奶油,覆盆子果茸,柠檬果茸','比利时,新西兰,法国,法国','<div><img src="img/products/details/1_1_4 (1).jpg" alt=""></div><div><img src="img/products/details/1_1_4 (2).jpg" alt=""></div><div><img src="img/products/details/1_1_4 (3).jpg" alt=""></div><div><img src="img/products/details/1_1_4 (4).jpg" alt=""></div><div class="fruit-details"><div class="fruitImg-details"><img src="img/products/details/cream.jpg" class="img-md"></div><div class="fruitTxt-details"><p>手工打发而成的美味奶油</p><p>口感绵密，精致细腻</p><p>这份雪白让你有如获至宝的幸福感</p></div></div><div class="fruit-details"><div class="fruitTxt-details"><p>剔透的色泽</p><p>让人联想到挂果的枝头</p><p>舌尖迷恋的这份清爽</p><p>恰是清甜的荔枝味道</p></div><div class="fruitImg-details"><img src="img/products/details/litchi.jpg" class="img-md"></div></div>',1);
INSERT INTO product_info VALUES(NULL,1,'敲敲话·巧克力流心蛋糕',NULL,'298蛋糕卡免差',318.00,'最早明天10:00配送','1539532800000',10,'巧克力味','1.0磅','5','约13.5×13.5cm','img/products/details/spec (1).png','适合3-4人分享','含5套餐具','0-4℃保藏10小时，5℃食用为佳','可可粉,黑巧克力,稀奶油','荷兰,比利时,新西兰','<div><img src="img/products/details/1_2_1 (3).jpg" alt=""></div><div><img src="img/products/details/1_2_1 (1).jpg" alt=""></div><div><img src="img/products/details/1_2_1 (2).jpg" alt=""></div><div class="fruit-details"><div class="fruitImg-details"><img src="img/products/details/cream.jpg" class="img-md"></div><div class="fruitTxt-details"><p>手工打发而成的美味奶油</p><p>口感绵密，精致细腻</p><p>这份雪白让你有如获至宝的幸福感</p></div></div><div class="fruit-details"><div class="fruitTxt-details"><p>进口的黑巧克力</p><p>通过精湛的工艺</p><p>将巧克力的香醇甜蜜</p><p>发挥至恰到好处</p><p>每一口都倍感甜蜜</p></div><div class="fruitImg-details"><img src="img/products/details/chocolate.jpg" class="img-md"></div></div>',1);
INSERT INTO product_info VALUES(NULL,1,'小甜鬼蛋糕',NULL,'NEW,万圣节限时99元',198.00,'最早明天10:00配送','1539532800000',10,'巧克力味','1.0磅','3','约13.5×13.5cm','img/products/details/spec (1).png','适合3-4人分享','含5套餐具','0-4℃保藏10小时，5℃食用为佳','可可粉,黑巧克力,淡奶油','荷兰,比利时,新西兰','<div><img src="img/products/details/1_2_2 (3).jpg" alt=""></div><div><img src="img/products/details/1_2_2 (1).jpg" alt=""></div><div><img src="img/products/details/1_2_2 (2).jpg" alt=""></div><div class="fruit-details"><div class="fruitImg-details"><img src="img/products/details/chocolate.jpg" class="img-md"></div><div class="fruitTxt-details"><p>进口的黑巧克力</p><p>通过精湛的工艺</p><p>将巧克力的香醇甜蜜</p><p>发挥至恰到好处</p><p>每一口都倍感甜蜜</p></div></div><div class="fruit-details"><div class="fruitTxt-details"><p>手工打发而成的美味奶油</p><p>口感绵密，精致细腻</p><p>这份雪白让你有如获至宝的幸福感</p></div><div class="fruitImg-details"><img src="img/products/details/cream.jpg" class="img-md"></div></div>',1);
INSERT INTO product_info VALUES(NULL,1,'公主蛋糕',NULL,'NEW,享198包邮',318.00,'最早明天10:00配送','1539532800000',10,'巧克力味','3.0磅','3','约22.5×22.5cm','img/products/details/spec (3).png','适合8-10人分享','含15套餐具','0-4℃保藏10小时，5℃食用为佳','白巧克力,淡奶油,黄油,幼砂糖','比利时,新西兰,新西兰,韩国','<div><img src="img/products/details/1_2_3 (1).jpg" alt=""></div><div><img src="img/products/details/1_2_3 (2).jpg" alt=""></div><div class="fruit-details"><div class="fruitImg-details"><img src="img/products/details/white_chocolate.jpg" class="img-md"></div><div class="fruitTxt-details"><p>选用进口白巧克力</p><p>精湛工艺将白巧克力擦出</p><p>如初雪般的轻柔</p><p>触碰舌尖即化，甜蜜动人</p></div></div><div class="fruit-details"><div class="fruitTxt-details"><p>手工打发而成的美味奶油</p><p>口感绵密，精致细腻</p><p>这份雪白让你有如获至宝的幸福感</p></div><div class="fruitImg-details"><img src="img/products/details/cream.jpg" class="img-md"></div></div>',1);
INSERT INTO product_info VALUES(NULL,1,'公主蛋糕',NULL,'NEW,享198包邮',488.00,'最早明天10:00配送','1539532800000',10,'巧克力味','4.0磅','3','约25.5×25.5cm','img/products/details/spec (4).png','适合10-12人分享','含20套餐具','0-4℃保藏10小时，5℃食用为佳','白巧克力,淡奶油,黄油,幼砂糖','比利时,新西兰,新西兰,韩国','<div><img src="img/products/details/1_2_3 (1).jpg" alt=""></div><div><img src="img/products/details/1_2_3 (2).jpg" alt=""></div><div class="fruit-details"><div class="fruitImg-details"><img src="img/products/details/white_chocolate.jpg" class="img-md"></div><div class="fruitTxt-details"><p>选用进口白巧克力</p><p>精湛工艺将白巧克力擦出</p><p>如初雪般的轻柔</p><p>触碰舌尖即化，甜蜜动人</p></div></div><div class="fruit-details"><div class="fruitTxt-details"><p>手工打发而成的美味奶油</p><p>口感绵密，精致细腻</p><p>这份雪白让你有如获至宝的幸福感</p></div><div class="fruitImg-details"><img src="img/products/details/cream.jpg" class="img-md"></div></div>',1);
INSERT INTO product_info VALUES(NULL,1,'公主蛋糕',NULL,'NEW,享198包邮',518.00,'最早明天10:00配送','1539532800000',10,'巧克力味','5.0磅','3','约28.5×28.5cm','img/products/details/spec (5).png','适合13-16人分享','含25套餐具','0-4℃保藏10小时，5℃食用为佳','白巧克力,淡奶油,黄油,幼砂糖','比利时,新西兰,新西兰,韩国','<div><img src="img/products/details/1_2_3 (1).jpg" alt=""></div><div><img src="img/products/details/1_2_3 (2).jpg" alt=""></div><div class="fruit-details"><div class="fruitImg-details"><img src="img/products/details/white_chocolate.jpg" class="img-md"></div><div class="fruitTxt-details"><p>选用进口白巧克力</p><p>精湛工艺将白巧克力擦出</p><p>如初雪般的轻柔</p><p>触碰舌尖即化，甜蜜动人</p></div></div><div class="fruit-details"><div class="fruitTxt-details"><p>手工打发而成的美味奶油</p><p>口感绵密，精致细腻</p><p>这份雪白让你有如获至宝的幸福感</p></div><div class="fruitImg-details"><img src="img/products/details/cream.jpg" class="img-md"></div></div>',1);
INSERT INTO product_info VALUES(NULL,1,'王子蛋糕',NULL,'NEW',318.00,'最早明天10:00配送','1539532800000',10,'巧克力味','3.0磅','3','约22.5×22.5cm','img/products/details/spec (3).png','适合8-10人分享','含15套餐具','0-4℃保藏10小时，5℃食用为佳','黑巧克力,淡奶油,黄油,幼砂糖','比利时,新西兰,新西兰,韩国','<div><img src="img/products/details/1_2_4 (1).jpg" alt=""></div><div><img src="img/products/details/1_2_4 (2).jpg" alt=""></div><div class="fruit-details"><div class="fruitImg-details"><img src="img/products/details/cream.jpg" class="img-md"></div><div class="fruitTxt-details"><p>手工打发而成的美味奶油</p><p>口感绵密，精致细腻</p><p>这份雪白让你有如获至宝的幸福感</p></div></div><div class="fruit-details"><div class="fruitTxt-details"><p>进口的黑巧克力</p><p>通过精湛的工艺</p><p>将巧克力的香醇甜蜜</p><p>发挥至恰到好处</p><p>每一口都倍感甜蜜</p></div><div class="fruitImg-details"><img src="img/products/details/chocolate.jpg" class="img-md"></div></div>',1);
INSERT INTO product_info VALUES(NULL,1,'王子蛋糕',NULL,'NEW',488.00,'最早明天10:00配送','1539532800000',10,'巧克力味','4.0磅','3','约25.5×25.5cm','img/products/details/spec (4).png','适合10-12人分享','含20套餐具','0-4℃保藏10小时，5℃食用为佳','黑巧克力,淡奶油,黄油,幼砂糖','比利时,新西兰,新西兰,韩国','<div><img src="img/products/details/1_2_4 (1).jpg" alt=""></div><div><img src="img/products/details/1_2_4 (2).jpg" alt=""></div><div class="fruit-details"><div class="fruitImg-details"><img src="img/products/details/cream.jpg" class="img-md"></div><div class="fruitTxt-details"><p>手工打发而成的美味奶油</p><p>口感绵密，精致细腻</p><p>这份雪白让你有如获至宝的幸福感</p></div></div><div class="fruit-details"><div class="fruitTxt-details"><p>进口的黑巧克力</p><p>通过精湛的工艺</p><p>将巧克力的香醇甜蜜</p><p>发挥至恰到好处</p><p>每一口都倍感甜蜜</p></div><div class="fruitImg-details"><img src="img/products/details/chocolate.jpg" class="img-md"></div></div>',1);
INSERT INTO product_info VALUES(NULL,1,'王子蛋糕',NULL,'NEW',518.00,'最早明天10:00配送','1539532800000',10,'巧克力味','5.0磅','3','约28.5×28.5cm','img/products/details/spec (5).png','适合13-16人分享','含25套餐具','0-4℃保藏10小时，5℃食用为佳','黑巧克力,淡奶油,黄油,幼砂糖','比利时,新西兰,新西兰,韩国','<div><img src="img/products/details/1_2_4 (1).jpg" alt=""></div><div><img src="img/products/details/1_2_4 (2).jpg" alt=""></div><div class="fruit-details"><div class="fruitImg-details"><img src="img/products/details/cream.jpg" class="img-md"></div><div class="fruitTxt-details"><p>手工打发而成的美味奶油</p><p>口感绵密，精致细腻</p><p>这份雪白让你有如获至宝的幸福感</p></div></div><div class="fruit-details"><div class="fruitTxt-details"><p>进口的黑巧克力</p><p>通过精湛的工艺</p><p>将巧克力的香醇甜蜜</p><p>发挥至恰到好处</p><p>每一口都倍感甜蜜</p></div><div class="fruitImg-details"><img src="img/products/details/chocolate.jpg" class="img-md"></div></div>',1);
INSERT INTO product_info VALUES(NULL,1,'巧克力松露蛋糕',NULL,'人气爆款',218.00,'最早明天10:00配送','1539532800000',10,'巧克力味','1.0磅','2','约13.5×13.5cm','img/products/details/spec (1).png','适合3-4人分享','含5套餐具','0-4℃保藏10小时，5℃食用为佳','黑巧克力,淡奶油,黄油,幼砂糖,牛奶','比利时,新西兰,新西兰,韩国,法国/德国','<div><img src="img/products/details/1_2_4 (1).jpg" alt=""></div><div><img src="img/products/details/1_2_4 (2).jpg" alt=""></div><div class="fruit-details"><div class="fruitImg-details"><img src="img/products/details/cream.jpg" class="img-md"></div><div class="fruitTxt-details"><p>手工打发而成的美味奶油</p><p>口感绵密，精致细腻</p><p>这份雪白让你有如获至宝的幸福感</p></div></div><div class="fruit-details"><div class="fruitTxt-details"><p>进口的黑巧克力</p><p>通过精湛的工艺</p><p>将巧克力的香醇甜蜜</p><p>发挥至恰到好处</p><p>每一口都倍感甜蜜</p></div><div class="fruitImg-details"><img src="img/products/details/chocolate.jpg" class="img-md"></div></div>',1);
INSERT INTO product_info VALUES(NULL,1,'巧克力松露蛋糕',NULL,'人气爆款',318.00,'最早明天10:00配送','1539532800000',10,'巧克力味','3.0磅','2','约22.5×22.5cm','img/products/details/spec (3).png','适合8-10人分享','含15套餐具','0-4℃保藏10小时，5℃食用为佳','黑巧克力,淡奶油,黄油,幼砂糖,牛奶','比利时,新西兰,新西兰,韩国,法国/德国','<div><img src="img/products/details/1_2_4 (1).jpg" alt=""></div><div><img src="img/products/details/1_2_4 (2).jpg" alt=""></div><div class="fruit-details"><div class="fruitImg-details"><img src="img/products/details/cream.jpg" class="img-md"></div><div class="fruitTxt-details"><p>手工打发而成的美味奶油</p><p>口感绵密，精致细腻</p><p>这份雪白让你有如获至宝的幸福感</p></div></div><div class="fruit-details"><div class="fruitTxt-details"><p>进口的黑巧克力</p><p>通过精湛的工艺</p><p>将巧克力的香醇甜蜜</p><p>发挥至恰到好处</p><p>每一口都倍感甜蜜</p></div><div class="fruitImg-details"><img src="img/products/details/chocolate.jpg" class="img-md"></div></div>',1);
INSERT INTO product_info VALUES(NULL,1,'巧克力松露蛋糕',NULL,'人气爆款',428.00,'最早明天10:00配送','1539532800000',10,'巧克力味','5.0磅','3','约28.5×28.5cm','img/products/details/spec (5).png','适合13-16人分享','含25套餐具','0-4℃保藏10小时，5℃食用为佳','黑巧克力,淡奶油,黄油,幼砂糖,牛奶','比利时,新西兰,新西兰,韩国,法国/德国','<div><img src="img/products/details/1_2_4 (1).jpg" alt=""></div><div><img src="img/products/details/1_2_4 (2).jpg" alt=""></div><div class="fruit-details"><div class="fruitImg-details"><img src="img/products/details/cream.jpg" class="img-md"></div><div class="fruitTxt-details"><p>手工打发而成的美味奶油</p><p>口感绵密，精致细腻</p><p>这份雪白让你有如获至宝的幸福感</p></div></div><div class="fruit-details"><div class="fruitTxt-details"><p>进口的黑巧克力</p><p>通过精湛的工艺</p><p>将巧克力的香醇甜蜜</p><p>发挥至恰到好处</p><p>每一口都倍感甜蜜</p></div><div class="fruitImg-details"><img src="img/products/details/chocolate.jpg" class="img-md"></div></div>',1);
INSERT INTO product_info VALUES(NULL,1,'数字蛋糕',NULL,'NEW',198.00,'最早明天10:00配送','1539532800000',10,'奶油口味','1.0磅','3','约13.5×13.5cm','img/products/details/spec (1).png','适合3-4人分享','含5套餐具','0-4℃保藏10小时，5℃食用为佳','樱桃味力娇酒,朗姆酒,淡奶油','荷兰,波多黎各,新西兰/法国','<div><img src="img/products/details/1_3_1 (3).jpg" alt=""></div><div><img src="img/products/details/1_3_1 (1).jpg" alt=""></div><div><img src="img/products/details/1_3_1 (2).jpg" alt=""></div><div><img src="img/products/details/1_3_1 (4).jpg" alt=""></div><div class="fruit-details"><div class="fruitImg-details"><img src="img/products/details/cream.jpg" class="img-md"></div><div class="fruitTxt-details"><p>手工打发而成的美味奶油</p><p>口感绵密，精致细腻</p><p>这份雪白让你有如获至宝的幸福感</p></div></div><div class="fruit-details"><div class="fruitTxt-details"><p>草莓薰红的季节</p><p>带来满口的酸甜</p><p>原汁原味</p><p>鲜丽诱人</p></div><div class="fruitImg-details"><img src="img/products/details/strawberry (2).jpg" class="img-md"></div></div><div class="fruit-details"><div class="fruitImg-details"><img src="img/products/details/blueberries.jpg" class="img-md"></div><div class="fruitTxt-details"><p>新鲜的蓝莓</p><p>与蛋糕的精心配比</p><p>酸甜清爽</p><p>回味无穷</p></div></div>',1);
INSERT INTO product_info VALUES(NULL,1,'数字蛋糕',NULL,'NEW',298.00,'最早明天10:00配送','1539532800000',10,'奶油口味','2.0磅','3','约17.5×17.5cm','img/products/details/spec (2).png','适合5-8人分享','含10套餐具','0-4℃保藏10小时，5℃食用为佳','樱桃味力娇酒,朗姆酒,淡奶油','荷兰,波多黎各,新西兰/法国','<div><img src="img/products/details/1_3_1 (3).jpg" alt=""></div><div><img src="img/products/details/1_3_1 (1).jpg" alt=""></div><div><img src="img/products/details/1_3_1 (2).jpg" alt=""></div><div><img src="img/products/details/1_3_1 (4).jpg" alt=""></div><div class="fruit-details"><div class="fruitImg-details"><img src="img/products/details/cream.jpg" class="img-md"></div><div class="fruitTxt-details"><p>手工打发而成的美味奶油</p><p>口感绵密，精致细腻</p><p>这份雪白让你有如获至宝的幸福感</p></div></div><div class="fruit-details"><div class="fruitTxt-details"><p>草莓薰红的季节</p><p>带来满口的酸甜</p><p>原汁原味</p><p>鲜丽诱人</p></div><div class="fruitImg-details"><img src="img/products/details/strawberry (2).jpg" class="img-md"></div></div><div class="fruit-details"><div class="fruitImg-details"><img src="img/products/details/blueberries.jpg" class="img-md"></div><div class="fruitTxt-details"><p>新鲜的蓝莓</p><p>与蛋糕的精心配比</p><p>酸甜清爽</p><p>回味无穷</p></div></div>',1);
INSERT INTO product_info VALUES(NULL,1,'怦然心动蛋糕',NULL,'HOT,人气爆款',198.00,'最早明天10:00配送','1539532800000',10,'奶油口味','1.0磅','2','约13.5×13.5cm','img/products/details/spec (1).png','适合3-4人分享','含5套餐具','0-4℃保藏10小时，5℃食用为佳','樱桃味力娇酒,朗姆酒,淡奶油','荷兰,波多黎各,新西兰/法国','<div><img src="img/products/details/1_3_2 (1).jpg" alt=""></div><div><img src="img/products/details/1_3_2 (2).jpg" alt=""></div><div class="fruit-details"><div class="fruitImg-details"><img src="img/products/details/cream.jpg" class="img-md"></div><div class="fruitTxt-details"><p>手工打发而成的美味奶油</p><p>口感绵密，精致细腻</p><p>这份雪白让你有如获至宝的幸福感</p></div></div><div class="fruit-details"><div class="fruitTxt-details"><p>草莓薰红的季节</p><p>带来满口的酸甜</p><p>原汁原味</p><p>鲜丽诱人</p></div><div class="fruitImg-details"><img src="img/products/details/strawberry (2).jpg" class="img-md"></div></div><div class="fruit-details"><div class="fruitImg-details"><img src="img/products/details/blueberries.jpg" class="img-md"></div><div class="fruitTxt-details"><p>新鲜的蓝莓</p><p>与蛋糕的精心配比</p><p>酸甜清爽</p><p>回味无穷</p></div></div>',1);
INSERT INTO product_info VALUES(NULL,1,'怦然心动蛋糕',NULL,'HOT,人气爆款',498.00,'最早明天10:00配送','1539532800000',10,'奶油口味','4.0磅','2','约25.5×25.5cm','img/products/details/spec (4).png','适合10-12人分享','含20套餐具','0-4℃保藏10小时，5℃食用为佳','樱桃味力娇酒,朗姆酒,淡奶油','荷兰,波多黎各,新西兰/法国','<div><img src="img/products/details/1_3_2 (1).jpg" alt=""></div><div><img src="img/products/details/1_3_2 (2).jpg" alt=""></div><div class="fruit-details"><div class="fruitImg-details"><img src="img/products/details/cream.jpg" class="img-md"></div><div class="fruitTxt-details"><p>手工打发而成的美味奶油</p><p>口感绵密，精致细腻</p><p>这份雪白让你有如获至宝的幸福感</p></div></div><div class="fruit-details"><div class="fruitTxt-details"><p>草莓薰红的季节</p><p>带来满口的酸甜</p><p>原汁原味</p><p>鲜丽诱人</p></div><div class="fruitImg-details"><img src="img/products/details/strawberry (2).jpg" class="img-md"></div></div><div class="fruit-details"><div class="fruitImg-details"><img src="img/products/details/blueberries.jpg" class="img-md"></div><div class="fruitTxt-details"><p>新鲜的蓝莓</p><p>与蛋糕的精心配比</p><p>酸甜清爽</p><p>回味无穷</p></div></div>',1);
INSERT INTO product_info VALUES(NULL,1,'花趣巧克力千层蛋糕',NULL,'NEW',298.00,'最早明天10:00配送','1539532800000',10,'奶油口味','3.0磅','5','约22.5×22.5cm','img/products/details/spec (3).png','适合8-10人分享','含15套餐具','0-4℃保藏10小时，5℃食用为佳','无盐黄油,稀奶油','新西兰,法国/德国','<div><img src="img/products/details/1_3_3 (1).jpg" alt=""></div><div><img src="img/products/details/1_3_3 (2).jpg" alt=""></div><div class="fruit-details"><div class="fruitImg-details"><img src="img/products/details/chocolate.jpg" class="img-md"></div><div class="fruitTxt-details"><p>进口的黑巧克力</p><p>通过精湛的工艺</p><p>将巧克力的香醇甜蜜</p><p>发挥至恰到好处</p><p>每一口都倍感甜蜜</p></div></div><div class="fruit-details"><div class="fruitTxt-details"><p>手工打发而成的美味奶油</p><p>口感绵密，精致细腻</p><p>这份雪白让你有如获至宝的幸福感</p></div><div class="fruitImg-details"><img src="img/products/details/cream.jpg" class="img-md"></div></div><div class="fruit-details"><div class="fruitImg-details"><img src="img/products/details/milk.jpg" class="img-md"></div><div class="fruitTxt-details"><p>黄金奶源地高品质奶源</p><p>香浓又健康</p><p>让你与大自然更亲近</p></div></div>',1);
INSERT INTO product_info VALUES(NULL,1,'雪域牛乳芝士蛋糕',NULL,'人气爆款',198.00,'最早明天10:00配送','1539532800000',10,'雪域口味','1.0磅','5','约13.5×13.5cm','img/products/details/spec (1).png','适合3-4人分享','含5套餐具','0-4℃保藏10小时，5℃食用为佳','无盐黄油,白巧克力,芝士,淡奶油','新西兰,比利时,新西兰,法国','<div><img src="img/products/details/1_4_1 (1).jpg" alt=""></div><div><img src="img/products/details/1_4_1 (2).jpg" alt=""></div><div class="fruit-details"><div class="fruitImg-details"><img src="img/products/details/cream.jpg" class="img-md"></div><div class="fruitTxt-details"><p>手工打发而成的美味奶油</p><p>口感绵密，精致细腻</p><p>这份雪白让你有如获至宝的幸福感</p></div></div><div class="fruit-details"><div class="fruitTxt-details"><p>选用进口白巧克力</p><p>精湛工艺将白巧克力擦出</p><p>如初雪般的轻柔</p><p>触碰舌尖即化，甜蜜动人</p></div><div class="fruitImg-details"><img src="img/products/details/white_chocolate.jpg" class="img-md"></div></div>',1);
INSERT INTO product_info VALUES(NULL,1,'雪域牛乳芝士蛋糕',NULL,'人气爆款',298.00,'最早明天10:00配送','1539532800000',10,'雪域口味','2.0磅','5','约17.5×17.5cm','img/products/details/spec (2).png','适合5-8人分享','含10套餐具','0-4℃保藏10小时，5℃食用为佳','无盐黄油,白巧克力,芝士,淡奶油','新西兰,比利时,新西兰,法国','<div><img src="img/products/details/1_4_1 (1).jpg" alt=""></div><div><img src="img/products/details/1_4_1 (2).jpg" alt=""></div><div class="fruit-details"><div class="fruitImg-details"><img src="img/products/details/cream.jpg" class="img-md"></div><div class="fruitTxt-details"><p>手工打发而成的美味奶油</p><p>口感绵密，精致细腻</p><p>这份雪白让你有如获至宝的幸福感</p></div></div><div class="fruit-details"><div class="fruitTxt-details"><p>选用进口白巧克力</p><p>精湛工艺将白巧克力擦出</p><p>如初雪般的轻柔</p><p>触碰舌尖即化，甜蜜动人</p></div><div class="fruitImg-details"><img src="img/products/details/white_chocolate.jpg" class="img-md"></div></div>',1);
INSERT INTO product_info VALUES(NULL,1,'雪域牛乳芝士蛋糕',NULL,'人气爆款',498.00,'最早明天10:00配送','1539532800000',10,'雪域口味','4.0磅','5','约25.5×25.5cm','img/products/details/spec (4).png','适合10-12人分享','含20套餐具','0-4℃保藏10小时，5℃食用为佳','无盐黄油,白巧克力,芝士,淡奶油','新西兰,比利时,新西兰,法国','<div><img src="img/products/details/1_4_1 (1).jpg" alt=""></div><div><img src="img/products/details/1_4_1 (2).jpg" alt=""></div><div class="fruit-details"><div class="fruitImg-details"><img src="img/products/details/cream.jpg" class="img-md"></div><div class="fruitTxt-details"><p>手工打发而成的美味奶油</p><p>口感绵密，精致细腻</p><p>这份雪白让你有如获至宝的幸福感</p></div></div><div class="fruit-details"><div class="fruitTxt-details"><p>选用进口白巧克力</p><p>精湛工艺将白巧克力擦出</p><p>如初雪般的轻柔</p><p>触碰舌尖即化，甜蜜动人</p></div><div class="fruitImg-details"><img src="img/products/details/white_chocolate.jpg" class="img-md"></div></div>',1);
INSERT INTO product_info VALUES(NULL,1,'雪域大理石芝士蛋糕',NULL,'HOT,NEW',398.00,'最早明天10:00配送','1539532800000',10,'雪域口味','3.0磅','2','约22.5×22.5cm','img/products/details/spec (3).png','适合8-10人分享','含15套餐具','0-4℃保藏10小时，5℃食用为佳','无盐黄油,白巧克力,芝士,淡奶油,黄油,幼砂糖','新西兰,比利时,新西兰,新西兰,新西兰,韩国/比利时','<div><img src="img/products/details/1_4_2 (1).jpg" alt=""></div><div><img src="img/products/details/1_4_2 (2).jpg" alt=""></div><div class="fruit-details"><div class="fruitImg-details"><img src="img/products/details/cream.jpg" class="img-md"></div><div class="fruitTxt-details"><p>手工打发而成的美味奶油</p><p>口感绵密，精致细腻</p><p>这份雪白让你有如获至宝的幸福感</p></div></div><div class="fruit-details"><div class="fruitTxt-details"><p>选用进口白巧克力</p><p>精湛工艺将白巧克力擦出</p><p>如初雪般的轻柔</p><p>触碰舌尖即化，甜蜜动人</p></div><div class="fruitImg-details"><img src="img/products/details/white_chocolate.jpg" class="img-md"></div></div>',1);
INSERT INTO product_info VALUES(NULL,1,'雪域大理石芝士蛋糕',NULL,'HOT,NEW',598.00,'最早明天10:00配送','1539532800000',10,'雪域口味','5.0磅','2','约28.5×28.5cm','img/products/details/spec (5).png','适合13-16人分享','含25套餐具','0-4℃保藏10小时，5℃食用为佳','无盐黄油,白巧克力,芝士,淡奶油,黄油,幼砂糖','新西兰,比利时,新西兰,新西兰,新西兰,韩国/比利时','<div><img src="img/products/details/1_4_2 (1).jpg" alt=""></div><div><img src="img/products/details/1_4_2 (2).jpg" alt=""></div><div class="fruit-details"><div class="fruitImg-details"><img src="img/products/details/cream.jpg" class="img-md"></div><div class="fruitTxt-details"><p>手工打发而成的美味奶油</p><p>口感绵密，精致细腻</p><p>这份雪白让你有如获至宝的幸福感</p></div></div><div class="fruit-details"><div class="fruitTxt-details"><p>选用进口白巧克力</p><p>精湛工艺将白巧克力擦出</p><p>如初雪般的轻柔</p><p>触碰舌尖即化，甜蜜动人</p></div><div class="fruitImg-details"><img src="img/products/details/white_chocolate.jpg" class="img-md"></div></div>',1);
INSERT INTO product_info VALUES(NULL,1,'牛乳蓝莓雪域双拼蛋糕',NULL,'HOT',198.00,'最早明天10:00配送','1539532800000',10,'雪域口味','1.0磅','3','约13.5×13.5cm','img/products/details/spec (1).png','适合3-4人分享','含5套餐具','0-4℃保藏10小时，5℃食用为佳','无盐黄油,白巧克力,芝士,淡奶油','新西兰,比利时,新西兰,法国','<div><img src="img/products/details/1_4_3 (2).jpg" alt=""></div><div><img src="img/products/details/1_4_3 (1).jpg" alt=""></div><div class="fruit-details"><div class="fruitImg-details"><img src="img/products/details/cream.jpg" class="img-md"></div><div class="fruitTxt-details"><p>手工打发而成的美味奶油</p><p>口感绵密，精致细腻</p><p>这份雪白让你有如获至宝的幸福感</p></div></div><div class="fruit-details"><div class="fruitTxt-details"><p>选用进口白巧克力</p><p>精湛工艺将白巧克力擦出</p><p>如初雪般的轻柔</p><p>触碰舌尖即化，甜蜜动人</p></div><div class="fruitImg-details"><img src="img/products/details/white_chocolate.jpg" class="img-md"></div></div><div class="fruit-details"><div class="fruitImg-details"><img src="img/products/details/blueberries.jpg" class="img-md"></div><div class="fruitTxt-details"><p>新鲜的蓝莓</p><p>与蛋糕的精心配比</p><p>酸甜清爽</p><p>回味无穷</p></div></div>',1);
INSERT INTO product_info VALUES(NULL,1,'环游世界·秋冬季蛋糕',NULL,'人气爆款',218.00,'最早明天10:00配送','1539532800000',10,'慕斯口味','1.0磅','1','约13.5×13.5cm','img/products/details/spec (1).png','适合3-4人分享','含5套餐具','0-4℃保藏10小时，5℃食用为佳','烤巴旦木片,稀奶油,奶油芝士,黑巧克力,马斯卡邦尼芝士','美国,新西兰,新西兰,比利时,意大利','<div><img src="img/products/details/1_5_1 (2).jpg" alt=""></div><div><img src="img/products/details/1_5_1 (1).jpg" alt=""></div><div class="fruit-details"><div class="fruitImg-details"><img src="img/products/details/cream.jpg" class="img-md"></div><div class="fruitTxt-details"><p>手工打发而成的美味奶油</p><p>口感绵密，精致细腻</p><p>这份雪白让你有如获至宝的幸福感</p></div></div><div class="fruit-details"><div class="fruitTxt-details"><p>进口的黑巧克力</p><p>通过精湛的工艺</p><p>将巧克力的香醇甜蜜</p><p>发挥至恰到好处</p><p>每一口都倍感甜蜜</p></div><div class="fruitImg-details"><img src="img/products/details/chocolate.jpg" class="img-md"></div></div>',1);
INSERT INTO product_info VALUES(NULL,1,'环游世界·秋冬季蛋糕',NULL,'人气爆款',218.00,'最早明天10:00配送','1539532800000',10,'慕斯口味','2.0磅','1','约17.5×17.5cm','img/products/details/spec (2).png','适合5-8人分享','含5套餐具','0-4℃保藏10小时，5℃食用为佳','烤巴旦木片,稀奶油,奶油芝士,黑巧克力,马斯卡邦尼芝士','美国,新西兰,新西兰,比利时,意大利','<div><img src="img/products/details/1_5_1 (2).jpg" alt=""></div><div><img src="img/products/details/1_5_1 (1).jpg" alt=""></div><div class="fruit-details"><div class="fruitImg-details"><img src="img/products/details/cream.jpg" class="img-md"></div><div class="fruitTxt-details"><p>手工打发而成的美味奶油</p><p>口感绵密，精致细腻</p><p>这份雪白让你有如获至宝的幸福感</p></div></div><div class="fruit-details"><div class="fruitTxt-details"><p>进口的黑巧克力</p><p>通过精湛的工艺</p><p>将巧克力的香醇甜蜜</p><p>发挥至恰到好处</p><p>每一口都倍感甜蜜</p></div><div class="fruitImg-details"><img src="img/products/details/chocolate.jpg" class="img-md"></div></div>',1);
INSERT INTO product_info VALUES(NULL,1,'环游世界·秋冬季蛋糕',NULL,'人气爆款',218.00,'最早明天10:00配送','1539532800000',10,'慕斯口味','5.0磅','1','约28.5×28.5cm','img/products/details/spec (5).png','适合13-16人分享','含5套餐具','0-4℃保藏10小时，5℃食用为佳','烤巴旦木片,稀奶油,奶油芝士,黑巧克力,马斯卡邦尼芝士','美国,新西兰,新西兰,比利时,意大利','<div><img src="img/products/details/1_5_1 (2).jpg" alt=""></div><div><img src="img/products/details/1_5_1 (1).jpg" alt=""></div><div class="fruit-details"><div class="fruitImg-details"><img src="img/products/details/cream.jpg" class="img-md"></div><div class="fruitTxt-details"><p>手工打发而成的美味奶油</p><p>口感绵密，精致细腻</p><p>这份雪白让你有如获至宝的幸福感</p></div></div><div class="fruit-details"><div class="fruitTxt-details"><p>进口的黑巧克力</p><p>通过精湛的工艺</p><p>将巧克力的香醇甜蜜</p><p>发挥至恰到好处</p><p>每一口都倍感甜蜜</p></div><div class="fruitImg-details"><img src="img/products/details/chocolate.jpg" class="img-md"></div></div>',1);
INSERT INTO product_info VALUES(NULL,1,'提拉米苏乐脆蛋糕',NULL,'新品',198.00,'最早明天10:00配送','1539532800000',10,'慕斯口味','1.0磅','1','约13.5×13.5cm','img/products/details/spec (1).png','适合3-4人分享','含5套餐具','0-4℃保藏10小时，5℃食用为佳','黑巧克力,马斯卡邦尼芝士,牛奶巧克力,可可薄脆片','比利时,意大利,比利时,法国','<div><img src="img/products/details/1_5_2 (2).jpg" alt=""></div><div><img src="img/products/details/1_5_2 (1).jpg" alt=""></div><div class="fruit-details"><div class="fruitImg-details"><img src="img/products/details/chocolate.jpg" class="img-md"></div><div class="fruitTxt-details"><p>进口的黑巧克力</p><p>通过精湛的工艺</p><p>将巧克力的香醇甜蜜</p><p>发挥至恰到好处</p><p>每一口都倍感甜蜜</p></div></div><div class="fruit-details"><div class="fruitTxt-details"><p>选用上等芝士</p><p>加上独特的工艺</p><p>浓郁香滑</p><p>入口即溶</p></div><div class="fruitImg-details"><img src="img/products/details/cheese.jpg" class="img-md"></div></div>',1);
INSERT INTO product_info VALUES(NULL,1,'提拉米苏乐脆蛋糕',NULL,'新品',298.00,'最早明天10:00配送','1539532800000',10,'慕斯口味','2.0磅','1','约17.5×17.5cm','img/products/details/spec (2).png','适合5-8人分享','含10套餐具','0-4℃保藏10小时，5℃食用为佳','黑巧克力,马斯卡邦尼芝士,牛奶巧克力,可可薄脆片','比利时,意大利,比利时,法国','<div><img src="img/products/details/1_5_2 (2).jpg" alt=""></div><div><img src="img/products/details/1_5_2 (1).jpg" alt=""></div><div class="fruit-details"><div class="fruitImg-details"><img src="img/products/details/chocolate.jpg" class="img-md"></div><div class="fruitTxt-details"><p>进口的黑巧克力</p><p>通过精湛的工艺</p><p>将巧克力的香醇甜蜜</p><p>发挥至恰到好处</p><p>每一口都倍感甜蜜</p></div></div><div class="fruit-details"><div class="fruitTxt-details"><p>选用上等芝士</p><p>加上独特的工艺</p><p>浓郁香滑</p><p>入口即溶</p></div><div class="fruitImg-details"><img src="img/products/details/cheese.jpg" class="img-md"></div></div>',1);
INSERT INTO product_info VALUES(NULL,1,'玫瑰雪域芝士蛋糕',NULL,'新品',218.00,'最早明天10:00配送','1539532800000',10,'芝士口味','2.0磅','5','约17.5×17.5cm','img/products/details/spec (2).png','适合5-8人分享','含10套餐具','0-4℃保藏10小时，5℃食用为佳','芝士,黄油,白巧克力,淡奶油,幼砂糖','新西兰,新西兰,比利时,新西兰,韩国','<div><img src="img/products/details/1_6_1 (2).jpg" alt=""></div><div><img src="img/products/details/1_6_1 (1).jpg" alt=""></div><div class="fruit-details"><div class="fruitImg-details"><img src="img/products/details/cream.jpg" class="img-md"></div><div class="fruitTxt-details"><p>手工打发而成的美味奶油</p><p>口感绵密，精致细腻</p><p>这份雪白让你有如获至宝的幸福感</p></div></div><div class="fruit-details"><div class="fruitTxt-details"><p>选用上等芝士</p><p>加上独特的工艺</p><p>浓郁香滑</p><p>入口即溶</p></div><div class="fruitImg-details"><img src="img/products/details/cheese.jpg" class="img-md"></div></div>',1);
INSERT INTO product_info VALUES(NULL,1,'玫瑰雪域芝士蛋糕',NULL,'新品',418.00,'最早明天10:00配送','1539532800000',10,'芝士口味','4.0磅','5','约28.5×28.5cm','img/products/details/spec (4).png','适合10-12人分享','含20套餐具','0-4℃保藏10小时，5℃食用为佳','芝士,黄油,白巧克力,淡奶油,幼砂糖','新西兰,新西兰,比利时,新西兰,韩国','<div><img src="img/products/details/1_6_1 (2).jpg" alt=""></div><div><img src="img/products/details/1_6_1 (1).jpg" alt=""></div><div class="fruit-details"><div class="fruitImg-details"><img src="img/products/details/cream.jpg" class="img-md"></div><div class="fruitTxt-details"><p>手工打发而成的美味奶油</p><p>口感绵密，精致细腻</p><p>这份雪白让你有如获至宝的幸福感</p></div></div><div class="fruit-details"><div class="fruitTxt-details"><p>选用上等芝士</p><p>加上独特的工艺</p><p>浓郁香滑</p><p>入口即溶</p></div><div class="fruitImg-details"><img src="img/products/details/cheese.jpg" class="img-md"></div></div>',1);
INSERT INTO product_info VALUES(NULL,1,'美刀刀蛋糕',NULL,'人气爆款',298.00,'最早明天10:00配送','1539532800000',10,'芝士口味','3.0磅','2','约22.5×22.5cm','img/products/details/spec (3).png','适合8-10人分享','含15套餐具','0-4℃保藏10小时，5℃食用为佳','奶油芝士,白巧克力,稀奶油','澳大利亚,比利时,新西兰','<div><img src="img/products/details/1_6_2 (2).jpg" alt=""></div><div><img src="img/products/details/1_6_2 (1).jpg" alt=""></div><div class="fruit-details"><div class="fruitImg-details"><img src="img/products/details/cream.jpg" class="img-md"></div><div class="fruitTxt-details"><p>手工打发而成的美味奶油</p><p>口感绵密，精致细腻</p><p>这份雪白让你有如获至宝的幸福感</p></div></div><div class="fruit-details"><div class="fruitTxt-details"><p>选用进口白巧克力</p><p>精湛工艺将白巧克力擦出</p><p>如初雪般的轻柔</p><p>触碰舌尖即化，甜蜜动人</p></div><div class="fruitImg-details"><img src="img/products/details/white_chocolate.jpg" class="img-md"></div></div>',1);
INSERT INTO product_info VALUES(NULL,1,'美刀刀蛋糕',NULL,'人气爆款',398.00,'最早明天10:00配送','1539532800000',10,'芝士口味','4.0磅','2','约25.5×25.5cm','img/products/details/spec (4).png','适合10-12人分享','含20套餐具','0-4℃保藏10小时，5℃食用为佳','奶油芝士,白巧克力,稀奶油','澳大利亚,比利时,新西兰','<div><img src="img/products/details/1_6_2 (2).jpg" alt=""></div><div><img src="img/products/details/1_6_2 (1).jpg" alt=""></div><div class="fruit-details"><div class="fruitImg-details"><img src="img/products/details/cream.jpg" class="img-md"></div><div class="fruitTxt-details"><p>手工打发而成的美味奶油</p><p>口感绵密，精致细腻</p><p>这份雪白让你有如获至宝的幸福感</p></div></div><div class="fruit-details"><div class="fruitTxt-details"><p>选用进口白巧克力</p><p>精湛工艺将白巧克力擦出</p><p>如初雪般的轻柔</p><p>触碰舌尖即化，甜蜜动人</p></div><div class="fruitImg-details"><img src="img/products/details/white_chocolate.jpg" class="img-md"></div></div>',1);
INSERT INTO product_info VALUES(NULL,1,'女神·冰淇淋蛋糕',NULL,'HOT,享198包邮,人气爆款',298.00,'最早明天10:00配送','1539532800000',10,'冰淇淋味','3.0磅','3','约22.5×22.5cm','img/products/details/spec (3).png','适合10-12人分享','含15套餐具','0-4℃保藏10小时，5℃食用为佳','白巧克力,可可粉,稀奶油,草莓巧克力','比利时,荷兰,法国,比利时','<div><img src="img/products/details/1_7_1 (2).jpg" alt=""></div><div><img src="img/products/details/1_7_1 (1).jpg" alt=""></div><div class="fruit-details"><div class="fruitImg-details"><img src="img/products/details/white_chocolate.jpg" class="img-md"></div><div class="fruitTxt-details"><p>选用进口白巧克力</p><p>精湛工艺将白巧克力擦出</p><p>如初雪般的轻柔</p><p>触碰舌尖即化，甜蜜动人</p></div></div>',1);
INSERT INTO product_info VALUES(NULL,1,'男神·冰淇淋蛋糕',NULL,'HOT,享198包邮,人气爆款',198.00,'最早明天10:00配送','1539532800000',10,'冰淇淋味','2.0磅','3','约17.5×17.5cm','img/products/details/spec (2).png','适合5-8人分享','含10套餐具','0-4℃保藏10小时，5℃食用为佳','黑巧克力,幼砂糖,稀奶油','比利时,韩国,比利时','<div><img src="img/products/details/1_7_2 (2).jpg" alt=""></div><div><img src="img/products/details/1_7_2 (1).jpg" alt=""></div><div class="fruit-details"><div class="fruitImg-details"><img src="img/products/details/chocolate.jpg" class="img-md"></div><div class="fruitTxt-details"><p>进口的黑巧克力</p><p>通过精湛的工艺</p><p>将巧克力的香醇甜蜜</p><p>发挥至恰到好处</p><p>每一口都倍感甜蜜</p></div></div><div class="fruit-details"><div class="fruitTxt-details"><p>选用上等芝士</p><p>加上独特的工艺</p><p>浓郁香滑</p><p>入口即溶</p></div><div class="fruitImg-details"><img src="img/products/details/cheese.jpg" class="img-md"></div></div>',1);
INSERT INTO product_info VALUES(NULL,2,'熊抱原味匠心吐司（整条）',NULL,'HOT',78.00,'最早明天10:00配送','1539532800000',10,'吐司','2.0磅','2','约17.5×17.5cm','img/products/details/spec (2).png','适合5-8人分享','含10套餐具','常温，最多能保存4天','黄油片,幼砂糖,小麦细粉','法国,韩国,日本','<div><img src="img/products/details/2_1 (1).jpg" alt=""></div><div><img src="img/products/details/2_1 (2).jpg" alt=""></div><div class="fruit-details"><div class="fruitImg-details"><img src="img/products/details/flour.jpg" class="img-md"></div><div class="fruitTxt-details"><p>精选进口高筋小麦细粉</p><p>粉质细腻，均匀自然</p><p>带来浓郁麦香</p></div></div><div class="fruit-details"><div class="fruitTxt-details"><p>黄油像凝结的阳光</p><p>醇香细腻 入口即化</p><p>释放出柔滑清爽的本真滋味</p></div><div class="fruitImg-details"><img src="img/products/details/butter2.jpg" class="img-md"></div></div>',1);
INSERT INTO product_info VALUES(NULL,2,'莓你不行吐司（草莓风味半条装）',NULL,'HOT',58.00,'最早明天10:00配送','1539532800000',10,'吐司','1.0磅','2','约13.5×13.5cm','img/products/details/spec (1).png','适合3-4人分享','含5套餐具','常温，最多能保存4天','黄油片,幼砂糖,小麦细粉','法国,韩国,日本','<div><img src="img/products/details/2_2 (1).jpg" alt=""></div><div><img src="img/products/details/2_2 (2).jpg" alt=""></div><div class="fruit-details"><div class="fruitImg-details"><img src="img/products/details/flour.jpg" class="img-md"></div><div class="fruitTxt-details"><p>精选进口高筋小麦细粉</p><p>粉质细腻，均匀自然</p><p>带来浓郁麦香</p></div></div><div class="fruit-details"><div class="fruitTxt-details"><p>黄油像凝结的阳光</p><p>醇香细腻 入口即化</p><p>释放出柔滑清爽的本真滋味</p></div><div class="fruitImg-details"><img src="img/products/details/butter2.jpg" class="img-md"></div></div>',1);
INSERT INTO product_info VALUES(NULL,2,'哇哦！吐司',NULL,'HOT',78.00,'最早明天10:00配送','1539532800000',10,'吐司','2.0磅','2','约17.5×17.5cm','img/products/details/spec (2).png','适合5-8人分享','含10套餐具','常温，最多能保存4天','黄油片,幼砂糖,小麦细粉,无盐黄油','法国,韩国,日本,新西兰','<div><img src="img/products/details/2_3 (1).jpg" alt=""></div><div><img src="img/products/details/2_3 (2).jpg" alt=""></div><div class="fruit-details"><div class="fruitImg-details"><img src="img/products/details/orange.jpg" class="img-md"></div><div class="fruitTxt-details"><p>沁人心脾如琉璃般的橙皮丁</p><p>闪烁着 触动味蕾的香甜</p><p>轻轻咀嚼 交融在齿牙间</p><p>悠然的清爽之味尽在心中</p></div></div><div class="fruit-details"><div class="fruitTxt-details"><p>精选进口高筋小麦细粉</p><p>粉质细腻，均匀自然</p><p>带来浓郁麦香</p></div><div class="fruitImg-details"><img src="img/products/details/flour.jpg" class="img-md"></div></div><div class="fruit-details"><div class="fruitImg-details"><img src="img/products/details/butter2.jpg" class="img-md"></div><div class="fruitTxt-details"><p>黄油像凝结的阳光</p><p>醇香细腻 入口即化</p><p>释放出柔滑清爽的本真滋味</p></div></div>',1);
INSERT INTO product_info VALUES(NULL,2,'熊抱吐司经典套餐礼券包',NULL,'HOT,人气爆款',594.00,'最早明天10:00配送','1539532800000',10,'吐司','4.0磅','2','约25.5×25.5cm','img/products/details/spec (4).png','适合10-12人分享','含20套餐具','常温，最多能保存4天','稀奶油,黄油片,幼砂糖,小麦细粉,可可粉','法国,法国,韩国,日本,马来西亚','<div><img src="img/products/details/2_4 (2).jpg" alt=""></div><div><img src="img/products/details/2_4 (3).jpg" alt=""></div><div><img src="img/products/details/2_4 (1).jpg" alt=""></div><div class="fruit-details"><div class="fruitImg-details"><img src="img/products/details/Cocoa_powder.jpg" class="img-md"></div><div class="fruitTxt-details"><p>深色的可可粉里</p><p>蕴藏着优质可可豆的秘密</p><p>正挑起一场美味诱惑</p></div></div><div class="fruit-details"><div class="fruitTxt-details"><p>小小芝麻粒粒香脆</p><p>当颗粒被慢慢咀嚼</p><p>天然醇香飘然而出</p></div><div class="fruitImg-details"><img src="img/products/details/sesame.jpg" class="img-md"></div></div><div class="fruit-details"><div class="fruitImg-details"><img src="img/products/details/flour.jpg" class="img-md"></div><div class="fruitTxt-details"><p>精选进口高筋小麦细粉</p><p>粉质细腻，均匀自然</p><p>带来浓郁麦香</p></div></div><div class="fruit-details"><div class="fruitTxt-details"><p>黄油像凝结的阳光</p><p>醇香细腻 入口即化</p><p>释放出柔滑清爽的本真滋味</p></div><div class="fruitImg-details"><img src="img/products/details/butter2.jpg" class="img-md"></div></div>',1);
INSERT INTO product_info VALUES(NULL,3,'迷藏月饼礼盒（限定版）',NULL,'HOT,人气爆款',398.00,'最早明天10:00配送','1539532800000',10,'礼品','4.0磅','2','约25.5×25.5cm','img/products/details/spec (4).png','适合6-8人分享','一盒（8粒装）','常温，最多能保存60天','黄油,稀奶油','法国,新西兰','<div><img src="img/products/details/3_1 (4).gif" alt=""></div><div><img src="img/products/details/3_1 (3).gif" alt=""></div><div><img src="img/products/details/3_1 (1).gif" alt=""></div><div><img src="img/products/details/3_1 (2).gif" alt=""></div><div><img src="img/products/details/3_1 (1).jpg" alt=""></div><div class="fruit-details"><div class="fruitImg-details"><img src="img/products/details/milk2.jpg" class="img-md"></div><div class="fruitTxt-details"><p>甄选优质动物奶油</p><p>口感绵密，精致细腻</p><p>这份雪白让你有如获至宝的幸福感</p></div></div>',1);
INSERT INTO product_info VALUES(NULL,3,'费南雪金砖形礼盒（8枚入）',NULL,'NEW',128.00,'最早明天10:00配送','1539532800000',10,'礼品','1.0磅','2','约13.5×13.5cm','img/products/details/spec (1).png','适合3-4人分享','一盒（8枚片）','常温，最多能保存35天','黄油,低筋面粉','新西兰,香港','<div><img src="img/products/details/3_2 (3).jpg" alt=""></div><div><img src="img/products/details/3_2 (1).jpg" alt=""></div><div><img src="img/products/details/3_2 (2).jpg" alt=""></div><div class="fruit-details"><div class="fruitImg-details"><img src="img/products/details/butter.jpg" class="img-md"></div><div class="fruitTxt-details"><p>黄油像凝结的阳光</p><p>醇香细腻 入口即化</p><p>释放出柔滑清爽的本真滋味</p></div></div>',1);
INSERT INTO product_info VALUES(NULL,3,'千层蝴蝶酥·For Me（原味）',NULL,'NEW,新品',98.00,'最早明天10:00配送','1539532800000',10,'礼品','1.0磅','2','约13.5×13.5cm','img/products/details/spec (1).png','适合3-4人分享','一盒（16片）','常温，最多能保存2个月','黄油,牛奶','法国,澳洲','<div><img src="img/products/details/3_3 (1).jpg" alt=""></div><div><img src="img/products/details/3_3 (2).jpg" alt=""></div><div class="fruit-details"><div class="fruitImg-details"><img src="img/products/details/milk.jpg" class="img-md"></div><div class="fruitTxt-details"><p>黄金奶源地高品质奶源</p><p>香浓又健康</p><p>让你与大自然更亲近</p></div></div>',1);
INSERT INTO product_info VALUES(NULL,3,'乐熊熊曲奇礼盒',NULL,'NEW,新品',128.00,'最早明天10:00配送','1539532800000',10,'礼品','2.0磅','2','约17.5×17.5cm','img/products/details/spec (2).png','适合5-8人分享','一盒（40片）','常温，最多能保存3个月','无盐黄油,芝士粉','新西兰,美国','<div><img src="img/products/details/3_4 (1).jpg" alt=""></div><div><img src="img/products/details/3_4 (2).jpg" alt=""></div><div class="fruit-details"><div class="fruitImg-details"><img src="img/products/details/butter.jpg" class="img-md"></div><div class="fruitTxt-details"><p>黄油像凝结的阳光</p><p>醇香细腻 入口即化</p><p>释放出柔滑清爽的本真滋味</p></div></div>',1);
INSERT INTO product_info VALUES(NULL,3,'核桃曲奇礼盒（迷迭紫）',NULL,'HOT',98.00,'最早明天10:00配送','1539532800000',10,'礼品','1.0磅','2','约13.5×13.5cm','img/products/details/spec (1).png','适合3-4人分享','一盒（40片）','常温，最多能保存3个月','无盐黄油,巴旦木,核桃','新西兰,中国,中国','<div><img src="img/products/details/3_5 (2).jpg" alt=""></div><div><img src="img/products/details/3_5 (1).jpg" alt=""></div><div class="fruit-details"><div class="fruitImg-details"><img src="img/products/details/butter.jpg" class="img-md"></div><div class="fruitTxt-details"><p>黄油像凝结的阳光</p><p>醇香细腻 入口即化</p><p>释放出柔滑清爽的本真滋味</p></div></div>',1);

/*商品图片表*/
CREATE TABLE product_img_info(
	product_img_id INT PRIMARY KEY AUTO_INCREMENT, #商品图片编号
	pid INT,   #商品编号
	FOREIGN KEY(pid) REFERENCES product_info(product_id),
	md VARCHAR(128),   #商品中图片路径
	lg VARCHAR(128)   #商品大图片路径
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;
/*插入商品图片表数据*/
INSERT INTO product_img_info VALUES(NULL,1,'img/products/md/1_1_1.jpg','img/products/lg/1_1_1.jpg');
INSERT INTO product_img_info VALUES(NULL,2,'img/products/md/1_1_1.jpg','img/products/lg/1_1_1.jpg');
INSERT INTO product_img_info VALUES(NULL,3,'img/products/md/1_1_2.jpg','img/products/lg/1_1_2.jpg');
INSERT INTO product_img_info VALUES(NULL,4,'img/products/md/1_1_2.jpg','img/products/lg/1_1_2.jpg');
INSERT INTO product_img_info VALUES(NULL,5,'img/products/md/1_1_2.jpg','img/products/lg/1_1_2.jpg');
INSERT INTO product_img_info VALUES(NULL,6,'img/products/md/1_1_2.jpg','img/products/lg/1_1_2.jpg');
INSERT INTO product_img_info VALUES(NULL,7,'img/products/md/1_1_3.jpg','img/products/lg/1_1_3.jpg');
INSERT INTO product_img_info VALUES(NULL,8,'img/products/md/1_1_3.jpg','img/products/lg/1_1_3.jpg');
INSERT INTO product_img_info VALUES(NULL,9,'img/products/md/1_1_3.jpg','img/products/lg/1_1_3.jpg');
INSERT INTO product_img_info VALUES(NULL,10,'img/products/md/1_1_3.jpg','img/products/lg/1_1_3.jpg');
INSERT INTO product_img_info VALUES(NULL,11,'img/products/md/1_1_4.jpg','img/products/lg/1_1_4.jpg');
INSERT INTO product_img_info VALUES(NULL,12,'img/products/md/1_2_1.jpg','img/products/lg/1_2_1 (1).jpg');
INSERT INTO product_img_info VALUES(NULL,12,'img/products/md/1_2_1.jpg','img/products/lg/1_2_1 (2).jpg');
INSERT INTO product_img_info VALUES(NULL,13,'img/products/md/1_2_2.jpg','img/products/lg/1_2_2.jpg');
INSERT INTO product_img_info VALUES(NULL,14,'img/products/md/1_2_3.jpg','img/products/lg/1_2_3.jpg');
INSERT INTO product_img_info VALUES(NULL,15,'img/products/md/1_2_3.jpg','img/products/lg/1_2_3.jpg');
INSERT INTO product_img_info VALUES(NULL,16,'img/products/md/1_2_3.jpg','img/products/lg/1_2_3.jpg');
INSERT INTO product_img_info VALUES(NULL,17,'img/products/md/1_2_4.jpg','img/products/lg/1_2_4.jpg');
INSERT INTO product_img_info VALUES(NULL,18,'img/products/md/1_2_4.jpg','img/products/lg/1_2_4.jpg');
INSERT INTO product_img_info VALUES(NULL,19,'img/products/md/1_2_4.jpg','img/products/lg/1_2_4.jpg');
INSERT INTO product_img_info VALUES(NULL,20,'img/products/md/1_2_5.jpg','img/products/lg/1_2_5.jpg');
INSERT INTO product_img_info VALUES(NULL,21,'img/products/md/1_2_5.jpg','img/products/lg/1_2_5.jpg');
INSERT INTO product_img_info VALUES(NULL,22,'img/products/md/1_2_5.jpg','img/products/lg/1_2_5.jpg');
INSERT INTO product_img_info VALUES(NULL,23,'img/products/md/1_3_1.jpg','img/products/lg/1_3_1 (1).jpg');
INSERT INTO product_img_info VALUES(NULL,23,'img/products/md/1_3_1.jpg','img/products/lg/1_3_1 (2).jpg');
INSERT INTO product_img_info VALUES(NULL,23,'img/products/md/1_3_1.jpg','img/products/lg/1_3_1 (3).jpg');
INSERT INTO product_img_info VALUES(NULL,23,'img/products/md/1_3_1.jpg','img/products/lg/1_3_1 (4).jpg');
INSERT INTO product_img_info VALUES(NULL,24,'img/products/md/1_3_1.jpg','img/products/lg/1_3_1 (1).jpg');
INSERT INTO product_img_info VALUES(NULL,24,'img/products/md/1_3_1.jpg','img/products/lg/1_3_1 (2).jpg');
INSERT INTO product_img_info VALUES(NULL,24,'img/products/md/1_3_1.jpg','img/products/lg/1_3_1 (3).jpg');
INSERT INTO product_img_info VALUES(NULL,24,'img/products/md/1_3_1.jpg','img/products/lg/1_3_1 (4).jpg');
INSERT INTO product_img_info VALUES(NULL,25,'img/products/md/1_3_2.jpg','img/products/lg/1_3_2.jpg');
INSERT INTO product_img_info VALUES(NULL,26,'img/products/md/1_3_2.jpg','img/products/lg/1_3_2.jpg');
INSERT INTO product_img_info VALUES(NULL,27,'img/products/md/1_3_3.jpg','img/products/lg/1_3_3.jpg');
INSERT INTO product_img_info VALUES(NULL,28,'img/products/md/1_4_1.jpg','img/products/lg/1_4_1.jpg');
INSERT INTO product_img_info VALUES(NULL,29,'img/products/md/1_4_1.jpg','img/products/lg/1_4_1.jpg');
INSERT INTO product_img_info VALUES(NULL,30,'img/products/md/1_4_1.jpg','img/products/lg/1_4_1.jpg');
INSERT INTO product_img_info VALUES(NULL,31,'img/products/md/1_4_2.jpg','img/products/lg/1_4_2.jpg');
INSERT INTO product_img_info VALUES(NULL,32,'img/products/md/1_4_2.jpg','img/products/lg/1_4_2.jpg');
INSERT INTO product_img_info VALUES(NULL,33,'img/products/md/1_4_3.jpg','img/products/lg/1_4_3.jpg');
INSERT INTO product_img_info VALUES(NULL,34,'img/products/md/1_5_1.jpg','img/products/lg/1_5_1.jpg');
INSERT INTO product_img_info VALUES(NULL,35,'img/products/md/1_5_1.jpg','img/products/lg/1_5_1.jpg');
INSERT INTO product_img_info VALUES(NULL,36,'img/products/md/1_5_1.jpg','img/products/lg/1_5_1.jpg');
INSERT INTO product_img_info VALUES(NULL,37,'img/products/md/1_5_2.jpg','img/products/lg/1_5_2.jpg');
INSERT INTO product_img_info VALUES(NULL,38,'img/products/md/1_5_2.jpg','img/products/lg/1_5_2.jpg');
INSERT INTO product_img_info VALUES(NULL,39,'img/products/md/1_6_1.jpg','img/products/lg/1_6_1.jpg');
INSERT INTO product_img_info VALUES(NULL,40,'img/products/md/1_6_1.jpg','img/products/lg/1_6_1.jpg');
INSERT INTO product_img_info VALUES(NULL,41,'img/products/md/1_6_2.jpg','img/products/lg/1_6_2.jpg');
INSERT INTO product_img_info VALUES(NULL,42,'img/products/md/1_6_2.jpg','img/products/lg/1_6_2.jpg');
INSERT INTO product_img_info VALUES(NULL,43,'img/products/md/1_7_1.jpg','img/products/lg/1_7_1.jpg');
INSERT INTO product_img_info VALUES(NULL,44,'img/products/md/1_7_2.jpg','img/products/lg/1_7_2.jpg');
INSERT INTO product_img_info VALUES(NULL,45,'img/products/md/2_1.jpg','img/products/lg/2_1 (1).jpg');
INSERT INTO product_img_info VALUES(NULL,45,'img/products/md/2_1.jpg','img/products/lg/2_1 (2).jpg');
INSERT INTO product_img_info VALUES(NULL,46,'img/products/md/2_2.jpg','img/products/lg/2_2.jpg');
INSERT INTO product_img_info VALUES(NULL,47,'img/products/md/2_3.jpg','img/products/lg/2_3.jpg');
INSERT INTO product_img_info VALUES(NULL,48,'img/products/md/2_4.jpg','img/products/lg/2_4 (1).jpg');
INSERT INTO product_img_info VALUES(NULL,48,'img/products/md/2_4.jpg','img/products/lg/2_4 (2).jpg');
INSERT INTO product_img_info VALUES(NULL,48,'img/products/md/2_4.jpg','img/products/lg/2_4 (3).jpg');
INSERT INTO product_img_info VALUES(NULL,48,'img/products/md/2_4.jpg','img/products/lg/2_4 (4).jpg');
INSERT INTO product_img_info VALUES(NULL,49,'img/products/md/3_1.jpg','img/products/lg/3_1.jpg');
INSERT INTO product_img_info VALUES(NULL,50,'img/products/md/3_2.jpg','img/products/lg/3_2 (1).jpg');
INSERT INTO product_img_info VALUES(NULL,50,'img/products/md/3_2.jpg','img/products/lg/3_2 (2).jpg');
INSERT INTO product_img_info VALUES(NULL,50,'img/products/md/3_2.jpg','img/products/lg/3_2 (3).jpg');
INSERT INTO product_img_info VALUES(NULL,51,'img/products/md/3_3.jpg','img/products/lg/3_3.jpg');
INSERT INTO product_img_info VALUES(NULL,52,'img/products/md/3_4.jpg','img/products/lg/3_4.jpg');
INSERT INTO product_img_info VALUES(NULL,53,'img/products/md/3_5.jpg','img/products/lg/3_5.jpg');

/*用户信息表*/
CREATE TABLE user_info(
	uid INT NOT NULL PRIMARY KEY AUTO_INCREMENT, #用户编号
	uname VARCHAR(32),                           #用户名称9**
	upwd  VARCHAR(32),                           #用户密码
	user_name VARCHAR(32),                       #用户真实姓名
	avatar VARCHAR(128),                         #用户图像
	gender TINYINT DEFAULT 1,                    #用户性别
	birth BIGINT,                                #用户生日
	phone VARCHAR(11),                           #手机号
	email VARCHAR(32)                            #邮箱
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;
/*插入用户信息表数据*/
INSERT INTO user_info VALUES(NULL,'dingding','123456','丁丁',null,0,0,'13576245310','1225431879@qq.com');
INSERT INTO user_info VALUES(NULL,'dangdang','987654','当当',null,1,0,'15634789152','1225431879@qq.com');
INSERT INTO user_info VALUES(NULL,'tom','123456','汤姆',null,1,0,'15678432015','1225431879@qq.com');
INSERT INTO user_info VALUES(NULL,'jerry','456123','杰瑞',null,0,0,'15648732015','1225431879@qq.com');
INSERT INTO user_info VALUES(NULL,'dongdong','123456','东东',null,1,0,'13575645310','1225431879@qq.com');

/*地址信息表*/
CREATE TABLE user_address_info(
	aid INT PRIMARY KEY AUTO_INCREMENT,  #用户地址编号
	user_id INT,                         #用户编号
	FOREIGN KEY(user_id) REFERENCES user_info(uid),
	recevier VARCHAR(32),                #收件人姓名
	phone VARCHAR(11) UNIQUE,            #手机号
	province VARCHAR(32),                #省
	city VARCHAR(32),                    #市
	county VARCHAR(32),                  #县
	address VARCHAR(128),                #详细地址
	postcode CHAR(6),                    #邮编
	is_default BOOLEAN DEFAULT 0         #是否为当前用户的默认收货地址
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;

/*购物车表*/
CREATE TABLE shopping_cart(
	cart_id INT PRIMARY KEY AUTO_INCREMENT, #购物车栏目编号
	user_id INT,                            #用户编号
	FOREIGN KEY(user_id) REFERENCES user_info(uid),
	pid INT,                         #商品编号
	FOREIGN KEY(pid) REFERENCES product_info(product_id),
	product_count INT                      #商品购买数量
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;

/*订单表*/
CREATE TABLE order_info(
	order_id INT PRIMARY KEY AUTO_INCREMENT,  #订单编号
	user_id INT,                              #用户编号
	FOREIGN KEY(user_id) REFERENCES user_info(uid),
	aid INT,                           #地址编号
	FOREIGN KEY(aid) REFERENCES user_address_info(aid),
	status INT,                               #订单状态 1-等待付款  2-等待发货  3-运输中  4-已签收  5-已取消  
	order_time BIGINT,                        #下单时间
	pay_time BIGINT,                          #付款时间
	deliver_time BIGINT,                      #发货时间
	recevied_time BIGINT                      #签收时间
)AUTO_INCREMENT=10000000 ENGINE=InnoDB DEFAULT CHARSET=UTF8;

/*订单详情表*/
CREATE TABLE order_detail_info(
	order_did INT PRIMARY KEY AUTO_INCREMENT, #订单栏目编号
	order_id INT,                             #订单编号
	FOREIGN KEY(order_id) REFERENCES order_info(order_id),
	pid INT,                           #商品编号
	FOREIGN KEY(pid) REFERENCES product_info(product_id),
	count INT                                #商品购买数量
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;

/*首页轮播图表*/
CREATE TABLE index_carousel(
	carousel_id INT PRIMARY KEY AUTO_INCREMENT,  #轮播图编号
	img VARCHAR(128),                            #图片路径
	title VARCHAR(64),                           #图片描述
	href VARCHAR(128)                            #图片链接
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;
INSERT INTO index_carousel VALUES(NULL,'img/index/banner_1.jpg','中秋月饼礼盒','product_details.html?product_id=49');
INSERT INTO index_carousel VALUES(NULL,'img/index/banner_2.jpg','提拉米苏乐脆蛋糕','product_details.html?product_id=37');
INSERT INTO index_carousel VALUES(NULL,'img/index/banner_3.jpg','怦然心动蛋糕','product_details.html?product_id=25');
INSERT INTO index_carousel VALUES(NULL,'img/index/banner_4.jpg','熊抱吐司经典套餐礼券包','product_details.html?product_id=48');
INSERT INTO index_carousel VALUES(NULL,'img/index/banner_5.jpg','女神·冰淇淋蛋糕','product_details.html?product_id=43');


/*首页产品表*/
CREATE TABLE index_product(
	index_product_id INT PRIMARY KEY AUTO_INCREMENT,  #主页商品编号
	pid INT,                                    #商品编号
	FOREIGN KEY(pid) REFERENCES product_info(product_id), 
	title VARCHAR(32),                          #商品标题
	subtitle VARCHAR(64),                       #商品副标题
	tag VARCHAR(64),                            #商品标签
	spec VARCHAR(32),                           #商品规格
	img VARCHAR(64),                            #商品图片路径
	price DECIMAL(10,2),                        #商品价格
	href VARCHAR(64)                            #商品链接
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;
INSERT INTO index_product VALUES(NULL,28,'雪域牛乳芝士蛋糕','特浓牛乳和新西兰上等芝士用独特的工艺','人气爆款','1.0磅','img/index/index_cake1.jpg',198.00,'product_details.html?product_id=28');
INSERT INTO index_product VALUES(NULL,23,'数字蛋糕','数字的蜜语你知多少','NEW','1.0磅','img/index/index_cake2.jpg',198.00,'product_details.html?product_id=23');
INSERT INTO index_product VALUES(NULL,41,'美刀刀蛋糕','芝士与香草戚风被雪域奶油的浪漫笼罩','人气爆款','3.0磅','img/index/index_cake3.jpg',298.00,'product_details.html?product_id=41');
INSERT INTO index_product VALUES(NULL,12,'敲敲话·巧克力流心蛋糕','悄悄话就藏在浓郁的巧克力中','298蛋糕卡免差','1.0磅','img/index/index_cake4.jpg',318.00,'product_details.html?product_id=12');
INSERT INTO index_product VALUES(NULL,11,'她的蛋糕','红丝绒里点缀上饱满的奇亚籽','HOT','2.0磅','img/index/index_cake5.jpg',298.00,'product_details.html?product_id=11');
INSERT INTO index_product VALUES(NULL,25,'怦然心动蛋糕','红丝绒与淡奶油层层交叠','HOT,人气爆款','1.0磅','img/index/index_cake6.jpg',198.00,'product_details.html?product_id=25');
INSERT INTO index_product VALUES(NULL,13,'小甜鬼蛋糕','慢慢融开比利时黑巧克力','NEW,万圣节限时99元','1.0磅','img/index/index_cake7.jpg',198.00,'product_details.html?product_id=13');
INSERT INTO index_product VALUES(NULL,37,'提拉米苏乐脆蛋糕','巧克力和咖啡的香浓滋味错落其间','新品','1.0磅','img/index/index_cake8.jpg',198.00,'product_details.html?product_id=37');
INSERT INTO index_product VALUES(NULL,45,'熊抱原味匠心吐司（整条）','原味吐司带你深入领略原汁原味的丹麦风','HOT','2.0磅','img/index/index_toast1.jpg',78.00,'product_details.html?product_id=45');
INSERT INTO index_product VALUES(NULL,46,'莓你不行吐司（草莓风味半条装）','淡淡的粉红色,甜甜的草莓味','HOT','1.0磅','img/index/index_toast2.jpg',58.00,'product_details.html?product_id=46');
INSERT INTO index_product VALUES(NULL,47,'哇哦！吐司','伴着桂花干与橙皮丁的甜香','HOT','2.0磅','img/index/index_toast3.jpg',78.00,'product_details.html?product_id=47');
INSERT INTO index_product VALUES(NULL,48,'熊抱吐司经典套餐礼券包','三色吐司每吃一口都能品出不同的诱人滋味','HOT,人气爆款','4.0磅','img/index/index_toast4.jpg',594.00,'product_details.html?product_id=48');
INSERT INTO index_product VALUES(NULL,49,'迷藏月饼礼盒（限定版）','法国总统黄油为月饼增添十足幼滑','HOT,人气爆款','4.0磅','img/index/index_gift1.jpg',398.00,'product_details.html?product_id=49');
INSERT INTO index_product VALUES(NULL,50,'费南雪金砖形礼盒（8枚入）','金砖的形状容易让人浮想联翩','NEW','1.0磅','img/index/index_gift2.jpg',128.00,'product_details.html?product_id=50');
INSERT INTO index_product VALUES(NULL,51,'千层蝴蝶酥·For Me（原味）','精心烘焙而成的蝴蝶酥','NEW','1.0磅','img/index/index_gift3.jpg',98.00,'product_details.html?product_id=51');
INSERT INTO index_product VALUES(NULL,52,'乐熊熊曲奇礼盒','从选材到造型,皆充满童真童趣','NEW','2.0磅','img/index/index_gift4.jpg',128.00,'product_details.html?product_id=52');

/*首页广告图表*/
CREATE TABLE index_ad(
	ad_id INT PRIMARY KEY AUTO_INCREMENT,      #广告图片编号
	img VARCHAR(128),                          #广告图片路径
	title VARCHAR(32),                         #广告图片描述
	href VARCHAR(128)                          #广告图片链接
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;
/*插入首页广告图表数据*/
INSERT INTO index_ad VALUES(NULL,'img/index/promote_1.jpg','蛋糕促销','product_details.html?product_id=23');
INSERT INTO index_ad VALUES(NULL,'img/index/promote_2.jpg','蛋糕促销','product_details.html?product_id=28');
INSERT INTO index_ad VALUES(NULL,'img/index/index_toast.jpg','吐司馆','product_details.html?product_id=45');
INSERT INTO index_ad VALUES(NULL,'img/index/index_gift.jpg','礼品馆','product_details.html?product_id=49');